### ISSUE TITLE
slide feature doesn't work when published on urls with a non "/" path

### ISSUE THREAD

**Issue by trylks** [logseq/publish-spa#11]
After exporting my graph, e.g. [here](https://trylks.github.io/bullets/#/page/tests), there are several things missing, most notably:

1. The presentation feature does not work. It is searching for Reveal.js:
    * Searching at: https://trylks.github.io/static/js/reveal.min.js
    * Actually located at: https://trylks.github.io/bullets/static/js/reveal.min.js (the name of the repo should be included)
2. The [Logseq - Diagrams as Code plugin](https://github.com/npgrosser/logseq-diagrams-as-code) does not work in this context. I do not even see an error searching for the corresponding JavaScript. I guess I should either:
    * Install the plugin locally and upload it to my GitHub repo (bullets), or
    * Specify in some configuration files the plugins to install so that Publish SPA will install them at build time. This would be great, but I could not find the corresponding documentation.

Am I missing something?

PD: This question is related to another [question at the Logseq - Diagrams as Code repo](https://github.com/npgrosser/logseq-diagrams-as-code/issues/25).

**Comment by logseq-cldwalker** [comment]
Hi. For plugins, they [only work on desktop](https://docs.logseq.com/#/page/plugins). If you'd like plugin support for web (and publishing apps), I'd recommend opening a feature request as [was done for mobile](https://discuss.logseq.com/t/plugin-support-for-ios-android-apps/10109/9).

For the [presentation/slide feature](https://docs.logseq.com/#/page/slide), it looks like it's an issue specific to paths that aren't "/" e.g. "bullets/" with your graph. You can see slides working at https://docs.logseq.com/#/page/contents. This isn't a high priority bug for us currently so contributions welcome in the meantime

**Comment by trylks** [comment]
Plugins: will do.

Presentation: Is [this replace](https://github.com/logseq/logseq/blob/62eb86f0c87275333279613171c76bc45f65421b/src/main/frontend/handler/assets.cljs#L57) the problem?

**Comment by trylks** [comment]
Plugins: will do.

Presentation: Is [this replace](https://github.com/logseq/logseq/blob/62eb86f0c87275333279613171c76bc45f65421b/src/main/frontend/handler/assets.cljs#L57) the problem?

**Comment by logseq-cldwalker** [comment]
@trylks Hi. If you update to the latest publish-spa version, 0.3.0 and configure the [version option](https://github.com/logseq/publish-spa#version) to `7525689bfb87009c752916e6a395dac6c64d11a6`, slides should work on your logseq graph
