### ISSUE TITLE
Aliases are not honored on SAP

### ISSUE THREAD

**Issue by StayPirate** [logseq/publish-spa#15]
### What Happened?

I uses page aliases in Logseq, which are working great locally. After this GH action has rendered and published those pages the aliases are no longer honored. Instead links points to unrefrerenced pages with the name of the alias.

### Reproduce the Bug

There's no need to reproduce the bug since all my work is public on [this repo](https://github.com/StayPirate/HTB-Notes) as well as GH action's log can be audited from [here](https://github.com/StayPirate/HTB-Notes/actions/workflows/publish.yml).

You can verify for instance that on [this block](https://staypirate.github.io/HTB-Notes/#/page/655ce01b-c0e5-4549-bbd9-9ec9747dc05a) I mention:

```
Retrieve [[ASREPRoast]] hashes
```

which is an alias for the [AS-REP Roasing](https://staypirate.github.io/HTB-Notes/#/page/as-rep%20roasting).

![image](https://github.com/logseq/publish-spa/assets/37073343/63f419f3-c4ae-4bd5-9204-8cf87a929f78)

Nevertheless, if you click on the link on the mentioned block it points to

`https://staypirate.github.io/HTB-Notes/#/page/asreproast`

instead of

`https://staypirate.github.io/HTB-Notes/#/page/as-rep%20roasting`

I want to highlight again that locally the alias works, the problem is only present on the published pages. Which makes me think that the bug should rely on this GH actions.
You can test that the alias locally works by cloning my repo and open it on you Logseq client.

### Expected Behavior

The aliases should be honored on the SAP the same way the Logseq client does.

### Desktop or Mobile Platform Information

I locally run Logseq v0.9.20 via Flatpak:

```
❯ flatpak info com.logseq.Logseq

Logseq - A local-first, non-linear, outliner notebook for organizing and
sharing your personal knowledge base

          ID: com.logseq.Logseq
         Ref: app/com.logseq.Logseq/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.9.20
     License: AGPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 425.3 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: bf636be62e77efc1b529f79eabaa6f5eac551da6141a2d8e98dbd2449782552d
      Parent: 34810510e13c9cf47043d5c10488a3eb3a028442ef2221f7bb6528fb0283f1f7
     Subject: Update runtime to 23.08 (0769284e)
        Date: 2023-11-11 18:36:41 +0000
```

**Comment by logseq-cldwalker** [comment]
0.3.0 has been released. Can you see if clicking on page ref aliases is working?

**Comment by StayPirate** [comment]
Problem solved, thank you!
