### ISSUE TITLE
"Filename too long" Error in github action

### ISSUE THREAD

**Issue by wxxb789** [logseq/publish-spa#17]
### What Happened?

Got a "Filename too long" error in github action

```plaintext
Checking out the ref
  /usr/bin/git checkout --progress --force -B main refs/remotes/origin/main
  Error: error: unable to create file pages/<a 160 chars chinese here>.org: File name too long
```

### Reproduce the Bug

submit a file with long filename to your repo.

**Comment by logseq-cldwalker** [comment]
Hi. This github action relies on git for versioning. If your graph is unable to work with git then unfortunately it won't work for this action. I'm happy to make this more explicit in the readme if that helps

**Comment by logseq-cldwalker** [comment]
Closing as I haven't heard back on improving documentation
