### ISSUE TITLE
GitLab CI example

### ISSUE THREAD

**Issue by almereyda** [logseq/publish-spa#18]
### What Happened?

logseq-publish had GitLab examples, and now redirects here. Unfortunately no GitLab-related discussion has yet arisen in the issues.

### Reproduce the Bug

1. Check logseq-publish GitLab examples
2. Find logseq-publish deprecated, linking here
3. Find no GitLab examples of logseq/publish-spa

### Expected Behavior

It could be nice to showcase how to build a LogSeq container in which this CLI runs, and use its image for building LogSeq pages from graphs stored in git repositories on GitLab.

### Desktop or Mobile Platform Information

N/A

**Comment by logseq-cldwalker** [comment]
Hi. I'm happy to take an example link like https://github.com/pengx17/logseq-publish for anyone who wants to work on this. https://github.com/logseq/publish-spa/blob/main/action.yml should be all that's needed to understand replicating this action on another service

**Comment by logseq-cldwalker** [comment]
There is now https://github.com/L-Trump/logseq-publish-docker for anyone who wants to contribute this documentation

**Comment by logseq-cldwalker** [comment]
Nice! I've linked to this example in the readme
