### ISSUE TITLE
Option to choose a default theme

### ISSUE THREAD

**Issue by dv0zn3r** [logseq/publish-spa#2]
Are there any options in yml available to enforce an always light/dark mode for a theme upon publishing a graph?

**Comment by logseq-cldwalker** [comment]
Hi. There aren't yet. I should be able to add this by the end of the week

**Comment by logseq-cldwalker** [comment]
Option has been added for this. If you want to try it out before the next release, use `logseq/publish-spa@main` for the action

**Comment by happylolonly** [comment]
Not working now https://github.com/logseq/publish-spa/issues/39
