### ISSUE TITLE
[Feature Request] Custom config.edn for export

### ISSUE THREAD

**Issue by HarvsG** [logseq/publish-spa#22]
### What Happened?

It would be helpful to either specify a seperate config.edn for export or to overwrite config.edn setting on export.
The particular use-case I imagine would be to specify a different home page. A typical user may just want their own home-page to be a journal entry or a page with links to common namespaces.
Whereas a public home page is more likely to either be a welcome page or a tutorial page on how to use the logseq graph

### Reproduce the Bug

FR

**Comment by HarvsG** [comment]
Created a related discussion on the forum that is regarding the Desktop export function: https://discuss.logseq.com/t/different-config-edn-on-export/24171

**Comment by logseq-cldwalker** [comment]
Hi. This can done without changes to the github action.  In your graph's `publish.yml`, simply add a step before the `- uses: logseq/publish-spa@v0.3.0` step, that copies your custom config.edn e.g. `- run: cp logseq/publishing-config.edn logseq/config.edn`

**Comment by logseq-cldwalker** [comment]
Hi. Closing as I haven't heard back. Hopefully my suggested workaround worked
