### ISSUE TITLE
Dockerfile for publish-spa

### ISSUE THREAD

**Issue by Alsouir** [logseq/publish-spa#28]
### What Happened?

Hello dear friend,  I'm writing a project for my university. I need to publish my website using Gitlab ci. And for this I am writing a dockerfile and my image takes up a lot of space of 5 GB. If I write this command in docker. My image is starting to take up a lot of space. How can I reduce the space occupied?

### Reproduce the Bug

FROM ubuntu
RUN mkdir publish-spa
COPY .  /publish-spa
RUN apt-get update && apt-get install curl -y & apt-get install -y -q --allow-unauthenticated git sudo && sudo apt install default-jdk
RUN curl -L -0 https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh && chmod +x linux-install.sh && sudo ./linux-install.sh
RUN curl -sL0 https://raw.githubusercontent.com/babashka/babashka/master/install && chmod +x install &/install
RUN curl -sSL https://deb.nodesource.com/setup_18.x | sudo bash -
RUN sudo apt install -y nodejs && node --version
RUN cd publish-spa && npm i -g
RUN npm install -g -y yarn
RUN git clone https://github.com/logseq/logseq && cd logseq & git checkout 0.10.6
WORKDIR /logseq
RUN yarn install --frozen-lockfile && yarn gulp:build && clojure -M:cljs release publishing
RUN yarn autoclean -i && yarn autoclean -f && yarn cache clean
WORKDIR /
RUN cp -r logseq publish-spa
WORKDIR /publish-spa
RUN npm install @logseq/nbb-logseq

```[tasklist]
### Tasks
```

**Comment by logseq-cldwalker** [comment]
Hi. I don't use docker with publish-spa so the best I can offer you are some guesses. After `clojure -M:cljs release publishing` is called you could try deleting logseq's `node_modules` to free up some disk space. You could also try the docker config at https://github.com/logseq/publish-spa/pull/29/files but it claims that it's size is ~7G

**Comment by L-Trump** [comment]
Hi. Since the publish-spa only use the static output of the logseq-lgoseq, a multi-stage Dockerfile can help reduce the image size. The final image size is at ~700 MB (alpine) and I've published it in ghcr.io. See https://github.com/L-Trump/logseq-publish-docker.

**Comment by logseq-cldwalker** [comment]
Closing this as this should be solved by logseq-publish-docker
