### ISSUE TITLE
A few menu and accessibility improvements...

### ISSUE THREAD

**Issue by necropolina** [logseq/publish-spa#3]
There's a few changes to the menu that would be really nice to have for published graphs...
- The `Add to Favorites`, `Unfavorite page`, and `Delete page` buttons don't do anything in published graphs, so they should be removed.
- The `Join the community` and `Bug report` buttons should also be removed because they are misleading. I'm using Logseq as a knowledge base for my software projects. If my users click "Join the community" they're probably trying to join a community related to my projects/organization. Similarly, if they click "Bug report" they're probably trying to report a bug in my own software rather than Logseq.
  - I would be fine with something more clear, like a "Made with Logseq" link being included somewhere, but those two options being in the menu are a problem.
- We need a "dark/light" mode toggle and the ability to set a default. It currently relies on the system theme to determine which to use, but this isn't good enough for a couple reasons:
  - It fails to recognize the theme for some operating systems, defaulting to light mode.
  - A lot of themes don't work for people and whether one does or not may depend on their physical environment. We need the ability to choose one that works. The ability for publishers to enable >2 theme options would be more ideal, but we need a light/dark toggle at the very least.

**Comment by logseq-cldwalker** [comment]
Hi. This repo just handles the github action part of publishing. Publishings issues are reported at https://github.com/logseq/logseq/issues e.g. https://github.com/logseq/logseq/labels/publishing. I'll update the readme or github issue form to make this clearer.

> We need a "dark/light" mode toggle and the ability to set a default

Yep. This was done for #2. There's not an official release for it yet but there are directions if you want to try it
