### ISSUE TITLE
Add a Dockerfile and publish to docker hub

### ISSUE THREAD

**Issue by daxartio** [logseq/publish-spa#5]
I think it will be useful for other ci systems

**Comment by logseq-cldwalker** [comment]
Hi. This github action doesn't rely on docker and we don't have bandwidth to build and maintain things we don't use. I'd be happy to link in the README to another project that would like to provide a docker version of action.yml. You can also use https://github.com/pengx17/logseq-publish for a docker approach. It is archived but should still be working

**Comment by daxartio** [comment]
I got it. Thanks!

I will try to make a docker version of action.yml
